const GET_DRAWER_OPEN = "GET_DRAWER_OPEN";
const TOGGLE_DRAWER_OPEN = "TOGGLE_DRAWER_OPEN";
const TOGGLE_DARK_MODE = "TOGGLE_DARK_MODE";
const GET_DARK_MODE = "GET_DARK_MODE";
const DISPLAY_SNACKBAR = "DISPLAY_SNACKBAR";
const RESET_SNACKBAR = "RESET_SNACKBAR";

export {
  GET_DRAWER_OPEN,
  TOGGLE_DRAWER_OPEN,
  GET_DARK_MODE,
  TOGGLE_DARK_MODE,
  DISPLAY_SNACKBAR,
  RESET_SNACKBAR,
};
